services:
  # Application
  app:
    container_name: koc-hub-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    working_dir: /home/koc-hub/koc-hub-server
    restart: unless-stopped
    tty: true
    env_file:
      - ../.env
    volumes:
      - ../:/home/koc-hub/koc-hub-server
    ports:
      - ${PORT}:${PORT}
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?schema=public
    networks:
      - koc-hub-server-network
    depends_on:
      - db

  # Database
  db:
    container_name: koc-hub-server-db
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    command: postgres -p ${DB_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - koc-hub-server-network

volumes:
  postgres:
    driver: local

networks:
  koc-hub-server-network:
    driver: bridge
